language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build"

before_deploy:
  - zip -r book-springboot2-webservice *
  - mkdir -p deploy
  - mv book-springboot2-webservice.zip deploy/book-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis Repo Settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis Repo Settings에 설정된 값

    bucket: book-springboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      branch: main


# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - chi4321@naver.com